apiVersion: v1
kind: ServiceAccount
metadata:
  name: snyk-reconciler
  namespace: snyk-reconciler
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pods-list
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get","watch","list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pods-list
subjects:
- kind: ServiceAccount
  name: snyk-reconciler
  namespace: snyk-reconciler
roleRef:
  kind: ClusterRole
  name: pods-list
  apiGroup: rbac.authorization.k8s.io
